export const booksDB = [
  {
    id: 1,
    author_name: "roxxanne",
    title: "Oliver Twist",
    cover_image: "https://loremflickr.com/170/270",
    pages: 234,
    releaseDate: "1839",
    isbn: "wt345",
    status: "read",
  },
  {
    id: 2,
    author_name: "roxxanne",
    title: "Hard Times",
    cover_image: "https://picsum.photos/200/300?random=3",
    pages: 300,
    releaseDate: "1854",
    isbn: "jk654",
    status: "reading",
  },
  {
    id: 3,
    author_name: "meow-kun",
    title: "Hamlet",
    cover_image: "https://picsum.photos/200/300?random=7",
    pages: 160,
    releaseDate: "1603",
    isbn: "po789",
    status: "reading",
  },
  {
    id: 4,
    author_name: "sanji",
    title: "IT",
    cover_image: "https://picsum.photos/seed/picsum/200/300",
    pages: 500,
    releaseDate: "2017",
    isbn: "yu098",
    status: "interested",
  },
  {
    id: 5,
    author_name: "zoro",
    title: "Norwegian Wood",
    cover_image:
      "http://t1.gstatic.com/images?q=tbn:ANd9GcQvJJDi2mzwg9v_PlmKYL31gXIz0kvAObJak7DVFPcD_mJTIyec",
    pages: 296,
    releaseDate: "1987",
    isbn: "hj846",
    status: "interested",
  },
  {
    id: 6,
    author_name: "sanji",
    title: "Kafka on the Shore",
    cover_image:
      "http://t0.gstatic.com/images?q=tbn:ANd9GcRHFU_j93PPsbQGqoaZJnHH6-Emk_sIxG823SkoRTL0nvdEP41f",
    pages: 505,
    releaseDate: "2002",
    isbn: "op012",
    status: "read",
  },
  {
    id: 7,
    author_name: "sanji",
    title: "After Dark",
    cover_image:
      "http://t3.gstatic.com/images?q=tbn:ANd9GcQBMNA8A19vQpNY4bkgadsLhiRUFqBKwKAA6ANrw8VEtOiPrYQJ",
    pages: 208,
    releaseDate: "2004",
    isbn: "cv456",
    status: "read",
  },
  {
    id: 8,
    author_name: "sanji",
    title: "1Q84",
    cover_image: "https://picsum.photos/200/300?random=8",
    pages: 928,
    releaseDate: "2009",
    isbn: "al207",
    status: "none",
  },
  {
    id: 9,
    author_name: "sanji",
    title: "Pikachu",
    cover_image: "https://picsum.photos/200/300?random=9",
    pages: 928,
    releaseDate: "2009",
    isbn: "al207",
    status: "none",
  },
  {
    id: 10,
    author_name: "sanji",
    title: "Pokemon",
    cover_image: "https://picsum.photos/200/300?random=6",
    pages: 928,
    releaseDate: "2009",
    isbn: "al207",
    status: "none",
  },
  {
    id: 11,
    author_name: "luffy",
    title: "Gomu Gomu",
    cover_image: "https://picsum.photos/200/300?random=10",
    pages: 928,
    releaseDate: "2009",
    isbn: "al207",
    status: "none",
  },
];
